metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: train.json
  dataset_dir: /data2/data_UAV/hongwai/
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: JPEGImages
  anno_path: val.json
  dataset_dir: /data2/data_UAV/hongwai/
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /data2/data_UAV/hongwai/ # if set, anno_path will be 'dataset_dir/anno_path'
