metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  image_dir: JpegImages
#  anno_path: annotations/instances_train.json
  anno_path: val.json
  dataset_dir: /data2/lqh/data/nishui/SeaDronesSee_CompressedVersion/
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: JpegImages
#  anno_path: annotations/instances_val.json
  anno_path: val.json
  dataset_dir: /data2/lqh/data/nishui/SeaDronesSee_CompressedVersion/
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /data2/lqh/data/nishui/SeaDronesSee_CompressedVersion/ # if set, anno_path will be 'dataset_dir/anno_path'
